### PR TITLE
Add AWS_Reference page

### PR DESCRIPTION
**Pull request by coliver0221**
Add resource of AWS_Reference page.

### CODE REVIEW

**Review by jserv — CHANGES_REQUESTED** [review]
Improve the git commit message. Check this: https://chris.beams.io/posts/git-commit/
At least, you should explain the items preserved within the changeset.

**Comment by yillkid** [comment]
No idea about the AWS Reference page, could you explain it? :)

**Comment by coliver0221** [comment]
> Improve the git commit message. Check this: https://chris.beams.io/posts/git-commit/
> At least, you should explain the items preserved within the changeset.

@jserv I have modified the commit message. Please check.

Thanks.

**Review by jserv — CHANGES_REQUESTED** [review]
All images files should appear in directory `/images/`.

**Comment by jserv** [comment]
> No idea about the AWS Reference page, could you explain it? :)

@coliver0221, you should modify the description of this pull request accordingly.

**Pull request merged**
